'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace ASPxEditorsTutorial


	Partial Public Class RegistrationForm

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' registrationFormLayout control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected registrationFormLayout As Global.DevExpress.Web.ASPxFormLayout.ASPxFormLayout

		''' <summary>
		''' firstNameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected firstNameTextBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' lastNameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lastNameTextBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' genderRadioButtonList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected genderRadioButtonList As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

		''' <summary>
		''' birthDateEdit control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected birthDateEdit As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

		''' <summary>
		''' countryComboBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected countryComboBox As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

		''' <summary>
		''' LayoutItemNestedControlContainer1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LayoutItemNestedControlContainer1 As Global.DevExpress.Web.ASPxFormLayout.LayoutItemNestedControlContainer

		''' <summary>
		''' cityComboBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cityComboBox As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

		''' <summary>
		''' eMailTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected eMailTextBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' passwordTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected passwordTextBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' ratingControl control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ratingControl As Global.DevExpress.Web.ASPxRatingControl.ASPxRatingControl

		''' <summary>
		''' ratingLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ratingLabel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' confirmPasswordTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected confirmPasswordTextBox As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' Captcha control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Captcha As Global.DevExpress.Web.ASPxEditors.ASPxCaptcha

		''' <summary>
		''' signUp control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected signUp As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' hyperLinkUsersPage control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected hyperLinkUsersPage As Global.DevExpress.Web.ASPxEditors.ASPxHyperLink

		''' <summary>
		''' AccessDataSourceCountry control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSourceCountry As Global.System.Web.UI.WebControls.AccessDataSource

		''' <summary>
		''' AccessDataSourceCities control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSourceCities As Global.System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
