'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace ASPxEditorsTutorial


	Partial Public Class RegistrationForm

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' registrationFormLayout control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected registrationFormLayout As Global.DevExpress.Web.ASPxFormLayout

		''' <summary>
		''' firstNameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected firstNameTextBox As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' lastNameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lastNameTextBox As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' genderRadioButtonList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected genderRadioButtonList As Global.DevExpress.Web.ASPxRadioButtonList

		''' <summary>
		''' birthDateEdit control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected birthDateEdit As Global.DevExpress.Web.ASPxDateEdit

		''' <summary>
		''' countryComboBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected countryComboBox As Global.DevExpress.Web.ASPxComboBox

		''' <summary>
		''' eMailTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected eMailTextBox As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' passwordTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected passwordTextBox As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' ratingControl control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ratingControl As Global.DevExpress.Web.ASPxRatingControl

		''' <summary>
		''' ratingLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ratingLabel As Global.DevExpress.Web.ASPxLabel

		''' <summary>
		''' LayoutItemNestedControlContainer1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer

		''' <summary>
		''' confirmPasswordTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected confirmPasswordTextBox As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' LayoutItemNestedControlContainer2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer

		''' <summary>
		''' Captcha control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Captcha As Global.DevExpress.Web.ASPxCaptcha

		''' <summary>
		''' LayoutItemNestedControlContainer3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer

		''' <summary>
		''' signUp control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected signUp As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' AccessDataSourceCountry control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected AccessDataSourceCountry As Global.System.Web.UI.WebControls.AccessDataSource
	End Class
End Namespace
